from __future__ import annotations

from pathlib import Path
import json
import re


def _read_palette(theme_dir: Path) -> dict:
    path = theme_dir / "palette.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _hex(palette: dict, key: str, fallback: str) -> str:
    return palette.get(key, fallback)


def apply_nvim(theme_dir: Path, config: Path):
    src = theme_dir / "nvim.lua"
    palette = _read_palette(theme_dir)
    if not src.exists() and not palette:
        return False

    config.mkdir(parents=True, exist_ok=True)
    target = config / "tedit_theme.lua"
    if src.exists():
        body = src.read_text(encoding="utf-8")
    else:
        p = palette
        body = f'''-- Generated by TEdit. Safe to remove.\nvim.g.tedit_theme = {theme_dir.name!r}\nvim.opt.termguicolors = true\nvim.cmd("highlight clear")\nvim.cmd("highlight Normal guibg={_hex(p, 'background', '#1e1e1e')} guifg={_hex(p, 'foreground', '#d4d4d4')}")\nvim.cmd("highlight NormalFloat guibg={_hex(p, 'surface', '#252526')} guifg={_hex(p, 'foreground', '#d4d4d4')}")\nvim.cmd("highlight LineNr guifg={_hex(p, 'muted', '#858585')}")\nvim.cmd("highlight CursorLineNr guifg={_hex(p, 'accent', '#569cd6')} gui=bold")\nvim.cmd("highlight Comment guifg={_hex(p, 'comment', '#6a9955')} gui=italic")\nvim.cmd("highlight String guifg={_hex(p, 'string', '#ce9178')}")\nvim.cmd("highlight Character guifg={_hex(p, 'string', '#ce9178')}")\nvim.cmd("highlight Number guifg={_hex(p, 'number', '#b5cea8')}")\nvim.cmd("highlight Boolean guifg={_hex(p, 'number', '#b5cea8')}")\nvim.cmd("highlight Keyword guifg={_hex(p, 'keyword', '#c586c0')}")\nvim.cmd("highlight Function guifg={_hex(p, 'function', '#dcdcaa')}")\nvim.cmd("highlight Type guifg={_hex(p, 'type', '#4ec9b0')}")\nvim.cmd("highlight Identifier guifg={_hex(p, 'variable', '#9cdcfe')}")\nvim.cmd("highlight Constant guifg={_hex(p, 'constant', '#4fc1ff')}")\nvim.cmd("highlight Visual guibg={_hex(p, 'selection', '#264f78')}")\nvim.cmd("highlight CursorLine guibg={_hex(p, 'line', '#2a2d2e')}")\n'''
    target.write_text(body, encoding="utf-8")

    init = config / "init.lua"
    marker_start = "-- TEDIT:BEGIN THEME"
    marker_end = "-- TEDIT:END THEME"
    block = f'{marker_start}\npcall(dofile, vim.fn.stdpath("config") .. "/tedit_theme.lua")\n{marker_end}'
    original = init.read_text(encoding="utf-8") if init.exists() else ""
    pattern = re.compile(re.escape(marker_start) + r".*?" + re.escape(marker_end), re.S)
    updated = pattern.sub(block, original) if pattern.search(original) else (original.rstrip() + "\n\n" + block + "\n")
    init.write_text(updated.lstrip("\n"), encoding="utf-8")
    return True


def apply_micro(theme_dir: Path, config: Path):
    src = theme_dir / "micro.json"
    if not src.exists():
        return False
    target = config / "colorschemes"
    target.mkdir(parents=True, exist_ok=True)
    (target / f"{theme_dir.name}.micro").write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
    return True


def apply_helix(theme_dir: Path, config: Path):
    src = theme_dir / "helix.toml"
    if not src.exists():
        return False
    target = config / "themes"
    target.mkdir(parents=True, exist_ok=True)
    (target / f"{theme_dir.name}.toml").write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
    return True


def _load_jsonc(path: Path) -> dict:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    # Conservative JSONC support for common settings.json files.
    text = re.sub(r"(^|\s)//.*?$", r"\1", text, flags=re.M)
    text = re.sub(r",\s*([}\]])", r"\1", text)
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Não foi possível editar {path}: JSON/JSONC inválido ({exc})") from exc


def apply_vscode(theme_dir: Path, config: Path):
    p = _read_palette(theme_dir)
    if not p:
        return False
    config.mkdir(parents=True, exist_ok=True)
    settings_path = config / "settings.json"
    settings = _load_jsonc(settings_path)

    colors = settings.setdefault("workbench.colorCustomizations", {})
    colors.update({
        "editor.background": _hex(p, "background", "#1e1e1e"),
        "editor.foreground": _hex(p, "foreground", "#d4d4d4"),
        "editorLineNumber.foreground": _hex(p, "muted", "#858585"),
        "editorCursor.foreground": _hex(p, "accent", "#aeafad"),
        "editor.selectionBackground": _hex(p, "selection", "#264f78"),
        "editor.lineHighlightBackground": _hex(p, "line", "#2a2d2e"),
        "editorWidget.background": _hex(p, "surface", "#252526"),
        "sideBar.background": _hex(p, "surface", "#252526"),
        "activityBar.background": _hex(p, "background", "#1e1e1e"),
        "statusBar.background": _hex(p, "surface", "#252526"),
    })
    settings["editor.tokenColorCustomizations"] = {
        "comments": _hex(p, "comment", "#6a9955"),
        "strings": _hex(p, "string", "#ce9178"),
        "numbers": _hex(p, "number", "#b5cea8"),
        "keywords": _hex(p, "keyword", "#c586c0"),
        "functions": _hex(p, "function", "#dcdcaa"),
        "variables": _hex(p, "variable", "#9cdcfe"),
        "types": _hex(p, "type", "#4ec9b0"),
    }
    settings_path.write_text(json.dumps(settings, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return True


def apply_atom(theme_dir: Path, config: Path):
    p = _read_palette(theme_dir)
    if not p:
        return False
    config.mkdir(parents=True, exist_ok=True)
    path = config / "styles.less"
    start, end = "// TEDIT:BEGIN THEME", "// TEDIT:END THEME"
    block = f'''{start}
atom-text-editor {{
  background-color: {_hex(p, 'background', '#282c34')};
  color: {_hex(p, 'foreground', '#abb2bf')};
}}
atom-text-editor .gutter {{ background-color: {_hex(p, 'surface', '#21252b')}; color: {_hex(p, 'muted', '#636d83')}; }}
.syntax--comment {{ color: {_hex(p, 'comment', '#5c6370')}; font-style: italic; }}
.syntax--string {{ color: {_hex(p, 'string', '#98c379')}; }}
.syntax--constant.syntax--numeric {{ color: {_hex(p, 'number', '#d19a66')}; }}
.syntax--keyword {{ color: {_hex(p, 'keyword', '#c678dd')}; }}
.syntax--entity.syntax--name.syntax--function {{ color: {_hex(p, 'function', '#61afef')}; }}
.syntax--storage.syntax--type, .syntax--support.syntax--type {{ color: {_hex(p, 'type', '#56b6c2')}; }}
{end}'''
    original = path.read_text(encoding="utf-8") if path.exists() else ""
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    updated = pattern.sub(block, original) if pattern.search(original) else original.rstrip() + "\n\n" + block + "\n"
    path.write_text(updated.lstrip("\n"), encoding="utf-8")
    return True


ADAPTERS = {
    "nvim": apply_nvim,
    "micro": apply_micro,
    "helix": apply_helix,
    "vscode": apply_vscode,
    "vscodium": apply_vscode,
    "atom": apply_atom,
    "pulsar": apply_atom,
}


def supports_theme(editor: str, theme_dir: Path) -> bool:
    if editor in {"vscode", "vscodium", "atom", "pulsar"}:
        return (theme_dir / "palette.json").exists()
    if editor == "nvim":
        return (theme_dir / "nvim.lua").exists() or (theme_dir / "palette.json").exists()
    if editor == "micro":
        return (theme_dir / "micro.json").exists()
    if editor == "helix":
        return (theme_dir / "helix.toml").exists()
    return False
